config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  root "static_pages#home"

  get "/signup", to: "users#new"
  get "/login", to: "logins#new"
  get "/static_pages", to: "static_pages#index"
  get "/home_notifications", to: "notifications#home"
  post "/login", to: "logins#create"
  delete "/logout", to: "logins#destroy"
  resources :users, except: [:destroy, :index]
  resources :account_activations, only: [:edit]
  resources :notifications, only: [:index]
  resources :passwords, only: [:new, :create, :edit, :update]
  resources :books, only: [:index, :show] do
    resources :user_books, only: %i(create update)
    resources :reviews, except: [:index] do
      resources :comments, except: [:index]
    end
  end

  namespace :admin do
    root "static_pages#index"

    resources :books, except: :show
    resources :users, except: :show
    resources :reviews, only: [:show, :index, :destroy]
  end
end

app/controllers/admin/static_pages_controller.rb
module Admin
  class StaticPagesController < AdminController
    def index
      @count_users = User.all.count
      @count_books = Book.all.count
      @count_reviews = Review.all.count
      @count_comments = Comment.all.count
      @count_user_activated = User.users_activated.count
      @count_user_dont_activated = User.users_dont_activated.count
      @count_month_reviews_array = find_arr_month_reviews
    end

    private

    def find_arr_month_reviews
      @year = Time.current.year
      @result_array = Array.new
      @reviews = Review.find_reviews_in_year((1.year.ago(Time.current)), (Time.current))
      if @reviews.any?
        (1..12).each do |i|
          count = 0
          @reviews.each do |review|
            count += 1 if (review.created_at.month == i && review.created_at.year == @year)
          end
          @result_array << count
        end
      else
        (1..12).each do |i|
          @result_array << 0
        end
      end
      return @result_array
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    @new_books = Book.top4_newest
    @top_is_favorite_books = Book.top_is_favorite_book
    @top_read_books = Book.top_read_book
    @newest_review = Review.last
    @new_comments = Comment.new_cmt
  end

  def index
    if params[:request] == "1"
      @title_request = "Giới thiệu"
      @id = 1
    elsif params[:request] == "2"
      @title_request = "Quy định của website"
      @id = 2
    elsif params[:request] == "3"
      @title_request = "Hướng dẫn đăng nhập"
      @id = 3
    elsif params[:request] == "4"
      @title_request = "Hướng dẫn đăng ký"
      @id = 4
    elsif params[:request] == "5"
      @title_request = "Hướng dẫn kích hoạt tài khoản"
      @id = 5
    elsif params[:request] == "6"
      @title_request = "Hướng dẫn thiết lập mật khẩu"
      @id = 6
    end
  end

  private

  def notification_params
    params.permit :request
  end
end

app/helpers/admin/static_pages_helper.rb
module Admin::StaticPagesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper

  def find_user_review user_id
    user = User.find_by id: user_id
    return user if user
  end

  def find_book_review book_id
    book = Book.find_by id: book_id
    return book if book
  end
end

app/views/static_pages/_image_welcome.html.erb
<% unless  logged_in? %>
  <div class="item">
    <article class="featured">
      <div class="overlay"></div>
      <figure>
        <img src="/assets/img-welcome.png" alt="Welcome" style="height: 100%;">
      </figure>
      <div class="details">
        <div class="category">
          <%= link_to "Đăng ký", signup_path %>
          <%= link_to "Đăng nhập", login_path %>
        </div>
        <h1>Đăng nhập để sử dụng đầy đủ các chức năng</h1>
      </div>
    </article>
  </div>
<% else %>
  <div class="item">
    <article class="featured">
      <div class="overlay"></div>
      <figure>
        <img src="/assets/img_life_skills.jpg" alt="Welcome" style="height: 100%;">
      </figure>
      <div class="details">
        <h1>Kho sách kỹ năng sống</h1>
      </div>
    </article>
  </div>
<% end %>

app/views/static_pages/_left.html.erb
<div class="col-md-8 col-sm-12 col-xs-12">
  <%= render "image_welcome" %>
  <%= render "new_books" %>
</div>

app/views/static_pages/_new_activities.html.erb
<aside>
  <ul class="nav nav-tabs nav-justified" role="tablist">
    <li class="active">
      <a href="#new_review" aria-controls="recomended" role="tab" data-toggle="tab">
        <i class="fa fa-star"></i> Bài đánh giá mới
      </a>
    </li>
    <li>
      <a href="#comments" aria-controls="comments" role="tab" data-toggle="tab">
        <i class="fa fa-comments"></i> Các bình luận mới
      </a>
    </li>
  </ul>
  <div class="tab-content">
    <div class="tab-pane active" id="new_review">
      <%= render "new_review" %>
    </div>
    <div class="tab-pane comments" id="comments">
      <%= render "new_comments" %>
    </div>
  </div>
</aside>

app/views/static_pages/_new_books.html.erb
<div class="line top">
  <div>Sách mới</div>
</div>
<div class="row">

  <% if @new_books.any? %>
    <% @new_books.each do |book| %>
      <article class="col-md-12 article-list">
        <div class="inner">
          <figure>
                <%= link_to book_path(book.id) do %>
                  <%= image_tag book.image.url, class: "book_cover", alt: "#{book.title}" %>
                <% end %>
          </figure>
          <div class="details">
            <div class="detail">
              <div class="category">
                <a href="javascript:void(0)">Ngày xuất bản:</a>
              </div>
              <div class="time"><%= book.publish_date.strftime("%d/%m/%Y") %></div>
            </div>
            <h1><%=link_to book.title, book_path(book.id) %></h1>
            <p><span class="text_title">Tác giả: </span><%= book.author %></p>
            <p><span class="text_title">Tóm tắt: </span>
              <span style="white-space: pre-line"><%= book.summary %></span>
            </p>
            <p><span class="text_title">Lượt thích: </span><%= count_favorite(book.id) %></p>
            <% book_star(book) %>
            <p><span class="text_title">Điểm đánh giá: </span><span style="color: red;"><%=@average%> </span>/ 5
            (<span style="color: green;"><%=@count_rate %></span> đánh giá)
            </p>
          </div>
        </div>
      </article>
    <% end %>
  <% else %>
    <h6 class="text_title" style="text-align: center;">Không tìm thấy sách</h6>
  <% end %>
</div>
<div class="line"></div>
<%= link_to books_path, class: "btn btn-magz white btn-block" do %>
  <span style="color: black;">Xem tất cả</span><i class="fa fa-angle-double-right"></i>
<% end %>

app/views/static_pages/_new_comments.html.erb
<div class="comment-list sm">
  <% if @new_comments.any? %>
    <% @new_comments.each do |comment| %>
      <% user = find_user_comment comment.user_id %>
      <%= link_to notifications_path(:comment_id => comment.id) do %>
        <div class="item">
          <div class="user">
            <figure>
              <%= gravatar_for user %>
            </figure>
            <div class="details">
              <h5 class="name"><%= user.full_name %></h5>
              <div class="time"><%= t "notify_time", time: time_ago_in_words(comment.created_at) %></div>
              <div class="description" style="color: black;">
                <%= comment.content %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
      <hr>
    <% end %>
  <% end %>
</div>

app/views/static_pages/_new_review.html.erb
<% if not @newest_review.nil? %>
  <% user = find_user_review @newest_review.user_id %>
  <% book = find_book_review @newest_review.book_id %>
  <article class="article-fw">
    <div class="">
      <%= link_to book_path(book.id) do %>
        <%= image_tag book.image.url, class: "book_cover_NewReview", alt: "#{book.title}" %>
      <% end %>
      <div class="details">
        <div class="detail">
          <div class="time">Ngày phát hành:   <%= book.publish_date.strftime("%d/%m/%Y") %></div>
        </div>
        <h5>Tiêu đề:
          <%= link_to book_path(book.id) do %>
            <%= book.title %>
          <% end %>
        </h5>
      </div>
    </div>
  </article>
  <div class="line"></div>
  <%= link_to notifications_path(:review_id => @newest_review.id) do %>
    <article class="article-mini">
      <div class="row">
        <div class="col-xs-6 col-sm-3">
          <figure style="width: 60px; height: 60px; border-radius: 50%;">
            <%= gravatar_for user %>
          </figure>
        </div>
        <div class="col-xs-9 col-sm-9">
            <h1>Được đánh giá bởi <span style="color: blue;"><%= user.full_name %></span></h1>
            <div class="detail">
              <span style="color: #8e8787;"><%= t "notify_time", time: time_ago_in_words(@newest_review.created_at) %></span>
            </div>
        </div>
      </div>
    </article>
  <% end %>
<% end %>

app/views/static_pages/_popular_books.html.erb
<aside>
  <h1 class="aside-title">Những cuốn sách được đọc nhiều</h1>
  <div class="aside-body">
    <% if @top_read_books.any? %>
      <% @top_read_books.each do |book| %>
        <article class="article-mini">
          <div class="inner">
            <figure>
              <%= link_to book_path(book.id) do %>
                <%= image_tag book.image.url, class: "book_cover_mini popular", alt: "#{book.title}" %>
              <% end %>
            </figure>
            <div class="padding">
              <h1 class="title_book_mini"><%= link_to book.title, book_path(book.id) %></h1>
              <p class="author_book_mini">Tác giả: <span><%= book.author %></span></p>
            </div>
          </div>
        </article>
      <% end %>
    <% end %>
  </div>
</aside>

app/views/static_pages/_right.html.erb
<div class="col-xs-6 col-md-4 sidebar" id="sidebar">
  <div class="sidebar-title for-tablet">Sidebar</div>
    <%= render "popular_books" %>
    <%= render "new_activities" %>
</div>

app/views/static_pages/home.html.erb
<% provide :title, "Trang chủ" %>
<div class="container">
  <div class="row">
    <%= render "left" %>
    <%= render "right" %>
  </div>
  <%= render "layouts/top4" %>
</div>

app/views/static_pages/index.html.erb
<% provide :title, @title_request %>
<div class="container">
  <div class="line top">
    <div><%= @title_request %></div>
  </div>
</div>