config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  root "static_pages#home"

  get "/signup", to: "users#new"
  get "/login", to: "logins#new"
  get "/static_pages", to: "static_pages#index"
  get "/home_notifications", to: "notifications#home"
  post "/login", to: "logins#create"
  delete "/logout", to: "logins#destroy"
  resources :users, except: [:destroy, :index]
  resources :account_activations, only: [:edit]
  resources :notifications, only: [:index]
  resources :passwords, only: [:new, :create, :edit, :update]
  resources :books, only: [:index, :show] do
    resources :user_books, only: %i(create update)
    resources :reviews, except: [:index] do
      resources :comments, except: [:index]
    end
  end

  namespace :admin do
    root "static_pages#index"

    resources :books, except: :show
    resources :users, except: :show
    resources :reviews, only: [:show, :index, :destroy]
  end
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :user_books, dependent: :destroy
  has_many :users, through: :user_books
  has_many :reviews, dependent: :destroy
  mount_uploader :image, ImageUploader

  validates :title, presence: {accept: true, message: "không được để trống"}
  validates :author, presence: {accept: true, message: "không được để trống"}
  validates :number_of_pages, numericality: {greater_than: 0, only_integer: true, message: "phải là một số nguyên dương"}
  validates :publish_date, presence: {accept: true, message: "không được để trống"}
  validates :summary, presence: {accept: true, message: "không được để trống"}

  scope :alpha, ->{order updated_at: :desc}
  scope :search_books, ->(text) do
    where("author LIKE ? or title LIKE ?", "%#{text}%", "%#{text}%") if text.present?
  end
  scope :top4_newest, ->{order(created_at: :desc).limit(4)}

  scope :new_book, ->{order(created_at: :desc)}

  scope :top_is_favorite_book, -> do
    joins(:user_books).where("is_favorite = true").group("books.id").order("count(is_favorite) desc").limit(4)
  end

  scope :favorite_book, -> do
    joins(:user_books).where("is_favorite = true").group("books.id").order("count(is_favorite) desc")
  end

  scope :your_favorite_book, -> (user_id) do
    joins(:user_books).where("is_favorite = true AND user_id = ?", user_id).order("updated_at desc") if user_id.present?
  end

  scope :your_mark_book, -> (user_id) do
    joins(:user_books).where("status != 0 AND user_id = ?", user_id).order("updated_at desc") if user_id.present?
  end

  scope :top_read_book, -> do
    joins(:user_books).where("status != 0").group("books.id").order("count(status) desc").limit(5)
  end

  scope :read_book, -> do
    joins(:user_books).where("status != 0").group("books.id").order("count(status) desc")
  end

  scope :count_favorite, -> (book_id) do
    joins(:user_books).where("is_favorite = true AND book_id = #{book_id}").select("count(books.id)")
  end
end

app/controllers/admin/books_controller.rb
module Admin
  class BooksController < AdminController
    before_action :find_book, except: %i(index new create)

    def index
      @books = Book.new_book.paginate page: params[:page], per_page: 5
    end

    def new
      @book = Book.new
    end

    def create
      @book = Book.new book_params
      if @book.save
        flash[:success] = "Thêm sách mới thành công"
        redirect_to admin_books_path
      else
        render :new
      end
    end

    def edit; end

    def update
      if @book.update_attributes book_params
        flash[:sucess] = "Cập nhật sách thành công"
        redirect_to admin_books_path
      else
        render :edit
      end
    end

    def destroy
      if @book.destroy
        flash[:success] = "Xóa sách thành công"
      else
        flash[:danger] = "Xóa sách không thành công"
      end
      redirect_to admin_books_path
    end

    private

    def book_params
      params.require(:book).permit :title, :author, :image, :publish_date, :number_of_pages, :summary
    end

    def find_book
      @book = Book.find_by id: params[:id]
      return if @book
      flash[:danger] = "Không tìm thấy sách"
      redirect_to admin_books_path
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :find_book, only: :show

  def index
    if params[:request]
      load_request_books params[:request]
    else
      if params[:search].blank?
        load_books
      else
        search_title_and_author
      end
    end
  end

  def book_params
    params.permit :search, :request
  end

  def show
    find_book_mark(params[:id], current_user.id) if logged_in?
    @reviews = @book.reviews.newest
    @reviews = collection_paginate @reviews, params[:page], 5
  end

  private

  def find_book
    @book = Book.find_by id: params[:id]
    return if @book
    flash[:danger] = "Không tìm thấy sách"
    redirect_to root_path
  end

  def search_title_and_author
    @books = Book.search_books params[:search]
    @books = collection_paginate @books, params[:page], 5
    @title_index = "Kết quả tìm kiếm cho " + "'#{params[:search]}'"
  end

  def find_book_mark book_id, user_id
    @user_book = UserBook.find_by book_id: book_id, user_id: user_id
    @notify_user_book = "Bạn chưa đánh dấu sách" if @user_book.nil?
  end

  def load_books
    @books = Book.alpha
    @books = collection_paginate @books, params[:page], 5
    @title_index = "Tất cả sách"
  end

  def load_request_books request
    if request == "love"
      @books = Book.favorite_book
      @title_index = "Sách được ưa thích nhiều nhất"
    elsif request == "new"
      @books = Book.new_book
      @title_index = "Sách mới"
    elsif request == "read"
      @books = Book.read_book
      @title_index = "Sách được đọc nhiều nhất"
    else
      if logged_in?
        if request == "loved"
          @books = Book.your_favorite_book current_user.id
          @title_index = "Sách ưa thích của bạn"
        else
          @books = Book.your_mark_book current_user.id
          @title_index = "Sách đã đánh dấu của bạn"
        end
      else
        redirect_back_or root_path
      end
    end
    @books = collection_paginate @books, params[:page], 5
  end
end

app/helpers/admin/books_helper.rb
module Admin::BooksHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/admin/books/edit.html.erb
<div class="container" style="padding-top: 89px;">
  <div class="box-wrapper">
    <div class="box box-border">
      <div class="box-body">
        <h4>Cập nhật thông tin sách</h4>
        <%= form_for [:admin,@book] do |f| %>
          <hr>
          <%= render "shared/error_messages", object: f.object %>

          <div class="form-group">
            <%= f.label :title, "Tiêu đề sách" %>
            <%= f.text_field :title, placeholder: "Nhập tên tiêu đề sách ...", class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :author, "Tác giả" %>
            <%= f.text_field :author, placeholder: "Nhập tên tác giả của sách ...", class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :publish_date, "Ngày xuất bản" %>
            <%= f.date_field :publish_date, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :number_of_pages, "Số trang" %>
            <%= f.number_field :number_of_pages, min: 1, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :image, "Ảnh bìa" %>
            <%= f.file_field :image, accept: "image/jpeg,image/gif,image/png", class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :summary, "Nội dung tóm tắt" %>
            <%= f.text_area :summary, id: "summary_book", placeholder: "Nhập nội dung tóm tắt của sách ...", class: "form-control" %>
          </div>
          <div class="form-group text-right">
            <%= f.submit "Thêm sách mới", class: "btn btn-primary btn-block" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
  $("#summary_book").on('input', function() {
    var scroll_height = $("#summary_book").get(0).scrollHeight;

    $("#summary_book").css('height', scroll_height + 'px');
  });
</script>

app/views/admin/books/index.html.erb
<div class="main-content-inner">
  <div class="page-content">
    <div class="page-header" style="margin-top: 0px;">
      <h4>
        Tất cả sách trong hệ thống
      </h4>
      <%= link_to new_admin_book_path do %>
        <button type="button" class="btn btn-info">Thêm sách mới</button>
      <% end %>
    </div>
    <div class="row">
      <div class="col-xs-12">
        <% flash.each do |mesage_type, mesage| %>
          <div class="alert alert-<%= mesage_type %> alert-dismissible fade in">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <strong>Thông báo:     </strong><%= mesage %>
          </div>
        <% end %>
        <div class="row content">
          <% if @books.any? %>
            <table id="table_books" class="table table-striped" style="width:100%">
              <thead>
                  <tr>
                      <th>Id sách</th>
                      <th>Tiêu đề</th>
                      <th>Tác giả</th>
                      <th>Số trang</th>
                      <th>Ngày tạo</th>
                      <th style="text-align: center;">Thao tác</th>
                  </tr>
              </thead>
              <tbody>
                <% @books.each do |book| %>
                  <tr>
                    <td><%= book.id %></td>
                    <td>
                      <%= link_to book_path(book.id) do %>
                        <%= book.title %>
                      <% end %>
                    </td>
                    <td><%= book.author %></td>
                    <td><%= book.number_of_pages %></td>
                    <td><%= book.created_at.strftime("%d/%m/%Y") %></td>
                    <td class="center">
                      <%= link_to edit_admin_book_path(book.id), class: "action_manage edit", title: "Cập nhật" do %>
                        <i class="fa fa-pencil" aria-hidden="true" style="color: green;"></i>
                      <% end %>
                      <%= link_to admin_book_path(book.id), method: :delete, data: {confirm: "Bạn có muốn xóa cuốn sách này không ?"},
                        class: "action_manage delete", title: "Xóa" do %>
                        <i class="fa fa-times-circle" aria-hidden="true" style="color: red;"></i>
                      <% end %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
            <script type="text/javascript">
              $(document).ready(function() {
                $('#table_books').DataTable();
              } );
            </script>
          <% else %>
            <p class="notify">Không có dữ liệu</p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/books/new.html.erb
<div class="container" style="padding-top: 89px;">
  <div class="box-wrapper">
    <div class="box box-border">
      <div class="box-body">
        <h4>Thêm sách mới</h4>
        <%= form_for [:admin,@book] do |f| %>
          <hr>
          <%= render "shared/error_messages", object: f.object %>

          <div class="form-group">
            <%= f.label :title, "Tiêu đề sách" %>
            <%= f.text_field :title, placeholder: "Nhập tên tiêu đề sách ...", class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :author, "Tác giả" %>
            <%= f.text_field :author, placeholder: "Nhập tên tác giả của sách ...", class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :publish_date, "Ngày xuất bản" %>
            <%= f.date_field :publish_date, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :number_of_pages, "Số trang" %>
            <%= f.number_field :number_of_pages, min: 1, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :image, "Ảnh bìa" %>
            <%= f.file_field :image, accept: "image/jpeg,image/gif,image/png", class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :summary, "Nội dung tóm tắt" %>
            <%= f.text_area :summary, id: "summary_book", placeholder: "Nhập nội dung tóm tắt của sách ...", class: "form-control" %>
          </div>
          <div class="form-group text-right">
            <%= f.submit "Thêm sách mới", class: "btn btn-primary btn-block" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
  $("#summary_book").on('input', function() {
    var scroll_height = $("#summary_book").get(0).scrollHeight;

    $("#summary_book").css('height', scroll_height + 'px');
  });
</script>