config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  root "static_pages#home"

  get "/signup", to: "users#new"
  get "/login", to: "logins#new"
  get "/static_pages", to: "static_pages#index"
  get "/home_notifications", to: "notifications#home"
  post "/login", to: "logins#create"
  delete "/logout", to: "logins#destroy"
  resources :users, except: [:destroy, :index]
  resources :account_activations, only: [:edit]
  resources :notifications, only: [:index]
  resources :passwords, only: [:new, :create, :edit, :update]
  resources :books, only: [:index, :show] do
    resources :user_books, only: %i(create update)
    resources :reviews, except: [:index] do
      resources :comments, except: [:index]
    end
  end

  namespace :admin do
    root "static_pages#index"

    resources :books, except: :show
    resources :users, except: :show
    resources :reviews, only: [:show, :index, :destroy]
  end
end

app/controllers/admin/reviews_controller.rb
module Admin
  class ReviewsController < ApplicationController
    before_action :find_review, only: [:show, :destroy]
    def index
      @reviews = Review.all
      respond_to do |format|
        format.html
        format.js
      end
    end

    def show
      respond_to do |format|
        format.html
        format.js
      end
    end

    def destroy
      if @review.destroy
        flash.now[:success] = "Xóa bài đánh giá thành công"
      else
        flash.now[:danger] = "Xóa bài đánh giá không thành công"
      end
      @reviews = Review.all
      respond_to do |format|
        format.html
        format.js
      end
    end

    private

    def find_review
      @review = Review.find_by id: params[:id]
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :logged_in_user, except: :show
  before_action :find_book
  before_action :check_review, only: :new
  before_action :find_review, except: %i(new create)

  def new
    @review = @book.reviews.build
  end

  def show
    find_comments @review
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @review = current_user.reviews.build review_params
    if @book.reviews << @review
      @activity = Activity.create(user_id: current_user.id, type_activity: "review", content: "Bạn đã đánh giá sách", object_id: @review.id)
      @reviews = Review.find_reviews_to_report(@review.book_id, current_user.id)
      if @reviews
        @reviews.each do |review|
          user = User.find_by id: review.user_id
          if user
            Notification.create(user_id: user.id, activity_id: @activity.id,
              content: current_user.full_name + " đã thêm đánh giá cho sách mà bạn đã tham gia đánh giá.")
          end
        end
      end
      flash[:success] = "Đăng bài thành công"
      redirect_to @book
    else
      render :new
    end
  end

  def edit
    respond_to do |format|
      format.html
      format.js
    end
  end

  def update
    if @review.update_attributes review_params
      Activity.create(user_id: current_user.id, type_activity: "review", content: "Bạn đã cập nhật bài đánh giá sách", object_id: @review.id)
      flash[:success] = "Cập nhập bài đánh giá thành công!"
    else
      flash[:danger] = "Cập nhập bài đánh giá không thành công! Vui lòng kiểm tra lại nội dung bài đánh giá."
    end
    redirect_to @book
  end

  def destroy
    if @review.destroy
      Activity.create(user_id: current_user.id, type_activity: "book", content: "Bạn đã xóa bài đánh giá sách", object_id: @book.id)
      flash[:success] = "Xóa bài đánh giá thành công!"
    else
      flash[:danger] = "Xóa bài đánh giá không thành công."
    end
    redirect_to @book
  end

  private

  def find_book
    @book = Book.find_by id: params[:book_id]
    return if @book
    flash[:danger] = "Không tìm thấy sách."
    redirect_to root_path
  end

  def reviewed user_id, book_id
    review = Review.find_by user_id: user_id, book_id: book_id
    return unless review
    flash[:danger] = "Bạn đã đánh giá cho quyển sách này. Bạn chỉ có thể cập nhật lại đánh giá."
    redirect_to @book
  end

  def check_review
    reviewed current_user.id, params[:book_id]
  end

  def review_params
    params.require(:review).permit :content, :rate, :book_id
  end

  def find_review
    @review = Review.find_by id: params[:id]
    redirect_to root_url if @review.nil?
  end

  def find_comments review
    @comments = Comment.list_cmt(review.id.to_s)
    return @notify_comment_empty = "Chưa có bình luận cho bài đánh giá." if @comments.empty?
  end
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
  def find_user_review review_id
    @review = Review.find_by id: review_id
    @user = User.find_by id: @review.user_id
    return @user if @user
  end

  def find_book_for_review review_id
    @review = Review.find_by id: review_id
    @book = Book.find_by id: @review.book_id
    return @book if @book
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
  def find_user_review user_id
    user = User.find_by id: user_id
    return user if user
  end

  def review_update? review
    return true if review.created_at < review.updated_at
    false
  end

  def correct_user_review? review
    return true if review.user_id == current_user.id
    false
  end

  def load_star_rating rate
    result = []
    (1..5).each do |n|
      if n <= rate
        result << (content_tag :span, nil, class: "fa fa-star set_color")
      else
        result << load_star_empty(n - rate)
      end
    end
    safe_join result
  end

  def load_star_empty value
    if value == 0.5
      content_tag :span, nil, class: "fa fa-star-half-empty set_color"
    else
      content_tag :span, nil, class: "fa fa-star-o set_color"
    end
  end
end

app/views/admin/reviews/_index.html.erb
<div class="main-content-inner">
  <div class="page-content">
    <div class="page-header" style="margin-top: 0px;">
      <h4>
        Danh sách bài đánh giá
      </h4>
    </div>
    <div class="row">
      <div class="col-xs-12">
        <% flash.each do |mesage_type, mesage| %>
          <div class="alert alert-<%= mesage_type %> alert-dismissible fade in">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <strong>Thông báo:     </strong><%= mesage %>
          </div>
        <% end %>
        <div class="row content">
          <% if @reviews.any? %>
            <table id="table_users" class="table table-striped" style="width:100%">
              <thead>
                  <tr>
                      <th>Người đánh giá</th>
                      <th>Sách được đánh giá</th>
                      <th>Ngày đánh giá</th>
                      <th style="text-align: center;">Hiển thị đánh giá</th>
                      <th style="text-align: center;">Xóa bài đánh giá</th>
                  </tr>
              </thead>
              <tbody>
                <% @reviews.each do |review| %>
                  <tr>
                    <td>
                      <% user = find_user_review(review.id) %>
                      <% if user %>
                        <%= link_to user_path(user.id) do %>
                          <%= user.full_name %>
                        <% end %>
                      <% else %>
                        Tên không xác định
                      <% end %>
                    </td>
                    <td>
                      <% book = find_book_for_review(review.id) %>
                      <% if book %>
                        <%= link_to book_path(book.id) do %>
                          <%= book.title %>
                        <% end %>
                      <% else %>
                        Tên sách không xác định
                      <% end %>
                    </td>
                    <td><%= review.created_at.strftime("%d/%m/%Y") %></td>
                    <td class="center">
                      <%= link_to admin_review_path(review.id), class: "action_manage edit",remote: true, title: "Xem" do %>
                        <i class="fa fa-eye" aria-hidden="true" style="color: green;"></i>
                      <% end %>
                    </td>
                    <td class="center">
                      <%= link_to admin_review_path(review.id), method: :delete, remote: true,
                        data: {confirm: "Bạn có muốn xóa bài đánh giá này không?"},
                        class: "action_manage delete", title: "Xóa" do %>
                        <i class="fa fa-times-circle" aria-hidden="true" style="color: red;"></i>
                      <% end %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
            <script type="text/javascript">
              $(document).ready(function() {
                $('#table_users').DataTable();
              } );
            </script>
          <% else %>
            <p class="notify">Không có dữ liệu</p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/reviews/_show.html.erb
<div class="main-content-inner">
  <div class="page-content">
    <div class="page-header" style="margin-top: 0px;">
      <h4>
        Nội dung bài đánh giá
      </h4>
      <% unless @review.nil? %>
        <%= link_to notifications_path(:review_id => @review.id) do %>
          <button type="button" class="btn btn-info">Xem các bình luận</button>
        <% end %>
      <% end %>
    </div>
    <div class="row">
      <div class="col-xs-12">
        <div class="row content">
          <div class="panel panel-default">
            <div class="panel-body">
              <% unless @review.nil? %>
                <span style="color: blue;">Nội dung:   </span><%= @review.content.html_safe %>
                <span style="color: blue;">Đánh giá sao:   </span><%= load_star_rating(@review.rate) %>
              <% else %>
                <p class="notify">Không có dữ liệu</p>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/reviews/destroy.js.erb
$('#box_content').html('<%= j(render('admin/reviews/index')) %>');

app/views/admin/reviews/index.js.erb
$('#box_content').html('<%= j(render('admin/reviews/index')) %>');

app/views/admin/reviews/show.js.erb
$('#box_content').html('<%= j(render('admin/reviews/show')) %>');