config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  root "static_pages#home"

  get "/signup", to: "users#new"
  get "/login", to: "logins#new"
  get "/static_pages", to: "static_pages#index"
  get "/home_notifications", to: "notifications#home"
  post "/login", to: "logins#create"
  delete "/logout", to: "logins#destroy"
  resources :users, except: [:destroy, :index]
  resources :account_activations, only: [:edit]
  resources :notifications, only: [:index]
  resources :passwords, only: [:new, :create, :edit, :update]
  resources :books, only: [:index, :show] do
    resources :user_books, only: %i(create update)
    resources :reviews, except: [:index] do
      resources :comments, except: [:index]
    end
  end

  namespace :admin do
    root "static_pages#index"

    resources :books, except: :show
    resources :users, except: :show
    resources :reviews, only: [:show, :index, :destroy]
  end
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  belongs_to :activity

  scope :new_notifications, -> (current_user_id) do
    where("user_id = ? AND is_see = false", current_user_id).order("created_at desc") if current_user_id.present?
  end

  scope :all_notifications, -> (current_user_id) do
    where("user_id = ?", current_user_id).order("created_at desc") if current_user_id.present?
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action -> {check_login_or_save_url('/home_notifications')}, only: [:home]

  def index
    if params[:review_id]
      find_review_and_book params[:review_id]
    elsif params[:comment_id]
      find_comment params[:comment_id]
      if @comment
        if @comment.id_comment_reply
          find_comment_replied @comment.id_comment_reply
          @id_comment_reply = @comment.id_comment_reply
          @show_cmt_reply = true
        else
          @show_cmt = true
        end
        find_review @comment.review_id
        if @review
          find_book @review.book_id
          @user_book = UserBook.find_by(user_id: current_user.id, book_id: @book.id)
        end
      end
    elsif (params[:activity_id] && params[:notify_id])
      @activity = Activity.find_by id: params[:activity_id]
      if @activity.type_activity == "book"
        @book = Book.find_by id: @activity.object_id
        if @book
          @user_book = UserBook.find_by(user_id: current_user.id, book_id: @book.id)
          @review = (Review.find_by book_id: @book.id).first
        end
      elsif @activity.type_activity == "review"
        find_review_and_book @activity.object_id
      else
        find_comment @activity.object_id
        if @comment
          if @comment.id_comment_reply
            find_comment_replied @comment.id_comment_reply
            @id_comment_reply = @comment.id_comment_reply
            @show_cmt_reply = true
          else
            @show_cmt = true
          end
          find_review @comment.review_id
          if @review
            find_book @review.book_id
            @user_book = UserBook.find_by(user_id: current_user.id, book_id: @book.id)
          end
        end
      end
      @notify = Notification.find_by id: params[:notify_id]
      @notify.update_attributes is_see: true
    else
      flash[:danger] = "Thao tác không thành công."
      redirect_to root_path
    end
  end

  def home
    @all_notifications = Notification.all_notifications current_user.id
    @all_notifications = collection_paginate @all_notifications, params[:page], 9
    @favorite_books = Book.your_favorite_book current_user.id
    @mark_read_books = Book.your_mark_book current_user.id
  end

  private

  def notification_params
    params.permit :review_id, :comment_id, :activity_id, :notify_id
  end

  def find_review_and_book review_id
    @review = Review.find_by id: review_id
    if @review.nil?
      flash[:danger] = "Không tìm thấy bài đánh giá."
      redirect_to root_url
    else
      find_book @review.book_id
      @user_book = UserBook.find_by(user_id: current_user.id, book_id: @book.id)
    end
  end

  def find_book book_id
    @book = Book.find_by id: book_id
    return if @book
    flash[:danger] = "Không tìm thấy sách."
    redirect_to root_path
  end

  def find_review review_id
    @review = Review.find_by id: review_id
    return if @review
    flash[:danger] = "Không tìm bài đánh giá."
    redirect_to root_path
  end

  def find_comment comment_id
    @comment = Comment.find_by id: comment_id
    return if @comment
    flash[:danger] = "Không tìm thấy bình luận."
    redirect_to root_path
  end

  def find_comment_replied id_comment_reply
    @comment_replied = Comment.find_by id: id_comment_reply
    return if @comment_replied
    flash[:danger] = "Không tìm thấy bình luận."
    redirect_to root_url
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_left_content.html.erb
<div class="col-md-8 col-sm-12 col-xs-12">
  <div class="line top">
    <div>Tất cả các thông báo</div>
  </div>
  <% if @all_notifications.any? %>
    <% @all_notifications.each do |notify| %>
      <div style="padding: 0px 18px;">
        <%= link_to notifications_path(:activity_id => notify.activity_id, :notify_id => notify.id) do %>
          <% if notify.is_see == false %>
            <p style="color: black;"><strong><%= notify.content %></strong></p>
          <% else %>
            <p style="color: black;"><%= notify.content %></p>
          <% end %>
        <% end %>
        <div class="detail" style="padding: 0px; margin: 0px;">
          <div style="color: #bbafaf;"><%= t "notify_time", time: time_ago_in_words(notify.created_at) %></div>
        </div>
      </div>
      <hr>
    <% end %>
    <%= will_paginate @all_notifications, id: "paginate" %>
  <% else %>
    <p style="color: blue;">Không có thông báo.</p>
  <% end %>

</div>

app/views/notifications/_right_content.html.erb
<div class="col-xs-6 col-md-4">
  <aside>
    <h1 class="aside-title">Một số sách được đánh dấu</h1>
    <ul class="nav nav-tabs nav-justified" role="tablist">
      <li class="active">
        <a href="#favorite_books" aria-controls="recomended" role="tab" data-toggle="tab">
          <i class="fa fa-star"></i> Sách ưa thích
        </a>
      </li>
      <li>
        <a href="#read_books" aria-controls="comments" role="tab" data-toggle="tab">
          <i class="fa fa-book"></i> Sách đánh dấu đọc
        </a>
      </li>
    </ul>
    <div class="tab-content">
      <div class="tab-pane active" id="favorite_books">
        <hr>
        <% if @favorite_books.any? %>
          <% count = 0 %>
          <% @favorite_books.each do |book| %>
            <article class="article-mini">
              <div class="inner">
                <figure>
                  <%= link_to book_path(book.id) do %>
                    <%= image_tag book.image.url, class: "book_cover_mini popular", alt: "#{book.title}" %>
                  <% end %>
                </figure>
                <div class="padding">
                  <%= link_to book_path(book.id) do %>
                    <h1><%= book.title %></h1>
                  <% end %>
                  <p class="author_book_mini">Tác giả: <span><%= book.author %></span></p>
                  <p style="color: #bbafaf; font-size: 10px;">
                    Ngày xuất bản: <span><%= book.publish_date.strftime("%d/%m/%Y") %>
                  </p>
                </div>
              </div>
            </article>
            <% count += 1 %>
            <% break if count == 7 %>
          <% end %>
          <% if @favorite_books.count > 7 %>
            <%= link_to "Xem tất cả", books_path(:request => "loved"), class: "see_all" %>
          <% end %>
        <% else %>
          <p>Bạn chưa đánh dấu sách ưa thích.</p>
        <% end %>
      </div>

      <div class="tab-pane comments" id="read_books">
        <hr>
        <% if @mark_read_books.any? %>
          <% count = 0 %>
          <% @mark_read_books.each do |book| %>
            <article class="article-mini">
              <div class="inner">
                <figure>
                  <%= link_to book_path(book.id) do %>
                    <%= image_tag book.image.url, class: "book_cover_mini popular", alt: "#{book.title}" %>
                  <% end %>
                </figure>
                <div class="padding">
                  <%= link_to book_path(book.id) do %>
                    <h1><%= book.title %></h1>
                  <% end %>
                  <p class="author_book_mini">Tác giả: <span><%= book.author %></span></p>
                  <p style="color: #bbafaf; font-size: 10px;">
                    Ngày xuất bản: <span><%= book.publish_date.strftime("%d/%m/%Y") %>
                  </p>
                </div>
              </div>
            </article>
            <% count += 1 %>
            <% break if count == 7 %>
          <% end %>
          <% if @mark_read_books.count > 7 %>
            <%= link_to "Xem tất cả", books_path(:request => "marked"), class: "see_all" %>
          <% end %>
        <% else %>
          <p>Bạn chưa đánh dấu sách đọc.</p>
        <% end %>
      </div>
    </div>
  </aside>
</div>

app/views/notifications/home.html.erb
<% provide :title, "Hiển thị các thông báo" %>
<div class="container">
  <div class="row">
  <%= render "notifications/left_content" %>
  <%= render "notifications/right_content"%>
  </div>
</div>

app/views/notifications/index.html.erb
<% if @book.nil? %>
  <% provide :title, "Chi tiết sách" %>
<% else %>
  <% provide :title, @book.title %>
<% end %>
<div class="container">
  <div class="line top">
    <div>Chi tiết sách</div>
  </div>

  <div class="row">
    <% if @book.nil? %>
      <h6 class="text_title" style="text-align: center;">Không tìm thấy sách</h6>
    <% else %>
      <div class="col-6 col-md-4">
        <%= link_to book_path(@book.id) do %>
          <%= image_tag @book.image.url, class: "book_cover_detail", alt: "#{@book.title}" %>
        <% end %>
      </div>
    <div class="col-12 col-md-8">
      <article class="col-md-12 article-list">
        <div class="details" style="margin: 0px;">
          <div class="detail">
            <div class="category">
              <a href="javascript:void(0)">Ngày xuất bản:</a>
            </div>
            <div class="time"><%= @book.publish_date.strftime("%d/%m/%Y") %></div>
          </div>
          <h1><%=link_to @book.title, book_path(@book.id) %></h1>
          <p><span class="text_title">Tác giả: </span><%= @book.author %></p>
          <p><span class="text_title">Số trang: </span><%= @book.number_of_pages %></p>
          <p><span class="text_title">Tóm tắt: </span><%= @book.summary.html_safe %></p>
          <hr>
          <h6>Đánh dấu sách của bạn</h6>
          <div id="mark_book">
            <%= render "user_books/mark_book" %>
          </div>
        </div>
      </article>
    </div>
    <% end %>
  </div>

  <div class="line thin"></div>

  <div class="comments">
    <h4 class="title write_review">Bài đánh giá
      <%= link_to "Viết bài đánh giá", new_book_review_path(@book.id) %>
    </h4>
    <hr>
    <div class="comment-list" id="show_review">
      <%= render "reviews/show_review" %>
    </div>
  </div>
</div>